spec-version: 0.30.0
name: halfsp
author: Asad Saeeduddin
maintainer: masaeedu@gmail.com
license: MIT

build-type: Simple

dependencies:
- { name: "base", version: '>=4.13 && <4.15' }

ghc-options: -Wall
default-extensions:
- GADTs

- StandaloneDeriving
- DeriveFunctor
- DerivingVia
- GeneralizedNewtypeDeriving

- ScopedTypeVariables
- RankNTypes
- QuantifiedConstraints

- TypeApplications
- TypeOperators
- MultiParamTypeClasses

- ConstraintKinds
- DataKinds
- PolyKinds
- KindSignatures

- UndecidableInstances
- FlexibleInstances
- FlexibleContexts
- DefaultSignatures

library:
  source-dirs: lib
  dependencies:
  - lsp
  - lsp-types
  - hiedb
  - aeson
  - sqlite-simple
  - filepath
  - text
  - string-conversions
  - ghc
  - microlens
  - hie-bios
  - array
  - containers
  - transformers
  - hashable

executable:
  source-dirs: app
  main: Main.hs
  dependencies:
  - halfsp

tests:
  halfsp-test:
    main: Main.hs
    source-dirs: test
    dependencies:
    - halfsp
    - tasty
    - tasty-discover
    - tasty-hunit
    - lsp-test
    build-tools:
    - tasty-discover
